POST http://localhost:8080/receipt/by/deposit
Content-Type: application/json

{
  "billSequenceId": "202401P000000001",
  "paymentId": "P000000001",
  "depositAmount": 1000,
  "accountNumber": "1010101010",
  "depositType": "CARD",
  "bank": "KB"
}
