POST http://localhost:8080/receipt/by/advancedPayment
Content-Type: application/json

{
  "billSequenceId": "202402P000000001",
  "paymentId": "P000000001",
  "advancedPaymentId": "ADVANCED-96102b61-fb4a-4832-bd5a-f300dc40a624"
}
